### ISSUE TITLE
UserDao类中users少写了一个s

### ISSUE THREAD

**Issue by Citadawn** [XQ-yang/JDBC#1]
UserDao类中sql语言的 users 少写了s，导致报错：  
Exception in thread "main" com.microsoft.sqlserver.jdbc.SQLServerException: 对象名 'user' 无效。

**Comment by XQ-yang** [comment]
> UserDao类中sql语言的 users 少写了s，导致报错： Exception in thread "main" com.microsoft.sqlserver.jdbc.SQLServerException: 对象名 'user' 无效。

数据库表名就是user，并没有users，是否是你未导入SQLServer的依赖？
